### ISSUE TITLE
Empty list/None incompatibility

### ISSUE THREAD

**Issue by rrthomas** [parkouss/pyewmh#6]
[This report was sent to me by someone without access to GitHub.]

There's a bunch of definitions like this one inside of `ewmh/ewmh.py`:

```
def getWmState(self, win, str=False):
    """Get the list of states of the given window (property _NET_WM_STATE).

    :param win: the window object
    :param str: True to get a list of string states instead of int
    :return: list of (int|str)"""
    states = self._getProperty('_NET_WM_STATE', win)
    if not str: return states
    return map(self._getAtomName, states)
```

The map(self._getAtomName, states) part fails when states is None. None is returned when no state is set.

Possible fixes: Either change `_getProperty` to return an empty Array when no properties are set or change that part, former seems more elegant to me.

**Comment by parkouss** [comment]
Thanks @rrthomas - also, there is an inconsistency between python3 and
python2 that I just discovered: python 2 map returns a list, while
python 3 returns an iterator;

I would happily take a PR to fix those - maybe at some point I will
fix it myself when I can find the time.

**Comment by parkouss** [comment]
fixed in https://github.com/parkouss/pyewmh/commit/c3fdbf3567b3767b3570fde48b5331a8f680ee82
