### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by rrthomas** [parkouss/pyewmh#7]
In the following:

    def getWmWindowType(self, win, str=False):
        """Get the list of window types of the given window (property _NET_WM_WINDOW_TYPE).

        :param win: the window object
        :param str: True to get a list of string types instead of int
        :return: list of (int|str)"""
        types = self._getProperty('_NET_WM_WINDOW_TYPE', win)
        if not str: return types
        return map(self._getAtomName, wtypes)

This seems to be a bug to me where `wtypes` is used at the last line instead of merely `types` but that bug hasn't bitten me yet so I'm not sure if this intended but it seems quite unlikely to be intended to me.

**Comment by parkouss** [comment]
Duplicates of #9.
