### ISSUE TITLE
Error at getWmWindowTypes

### ISSUE THREAD

**Issue by cpdef** [parkouss/pyewmh#9]
I think i found an bug at the getWmWindowTypes function:
`def getWmWindowType(self, win, str=False):
		"""Get the list of window types of the given window (property _NET_WM_WINDOW_TYPE).
		
		:param win: the window object
		:param str: True to get a list of string types instead of int
		:return: list of (int|str)"""
		types = self._getProperty('_NET_WM_WINDOW_TYPE', win)
		if not str: return types
		return map(self._getAtomName, wtypes)`
types at line 7 must be wtypes or wtypes at last line types. or not?

**Comment by parkouss** [comment]
I assume you are talking about the same fix reported in #7, and looks like there is a fix in #8. @rrthomas, I missed the bug report, sorry for that.

I'll give this a test, and will merge/release as soon as I find the time. Thanks!

**Comment by cpdef** [comment]
I thinked it was an other bug, i read wrong.

**Comment by cpdef** [comment]
Am 11.05.2016 um 21:06 schrieb Julien Pagès:
>
> I assume you are talking about the same fix reported in #7 
> <https://github.com/parkouss/pyewmh/issues/7>, and looks like there is 
> a fix in #8 <https://github.com/parkouss/pyewmh/pull/8>. @rrthomas 
> <https://github.com/rrthomas>, I missed the bug report, sorry for that.
>
> I'll give this a test, and will merge/release as soon as I find the 
> time. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/parkouss/pyewmh/issues/9#issuecomment-218558344>
>
I have read wrong, i thinked it was an other method. sorry.
But one Question: can u say me how to minimize a Window with emwh?
i tryed this:
[code]
from ewmh import EWMH
EWMH = EWMH()
win = EWMH.getActiveWindow()
EWMH.setWmState(win, 2, '_NET_WM_STATE_HIDDEN')
EWMH.display.flush()
[/code]
i know about a function XIconifyWindow in c and Xlib but i cant have 
access to this function via python.
Or is there some other function?


greetings Julian
